name: build

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - name: Setup Node 14.11.0
      uses: actions/setup-node@v1
      with:
        node-version: [12.18.4, 14.13.0]

    - name: Checkout from Git
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage
      run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        NEWGISTICS_AUTHAPI_URL: ${{ secrets.NEWGISTICS_AUTHAPI_URL }}
        NEWGISTICS_CLIENT_FACILITY_ID: ${{ secrets.NEWGISTICS_CLIENT_FACILITY_ID }}
        NEWGISTICS_CLIENT_ID: ${{ secrets.NEWGISTICS_CLIENT_ID }}
        NEWGISTICS_CLIENT_SECRET: ${{ secrets.NEWGISTICS_CLIENT_SECRET }}
        NEWGISTICS_FACILITY_ID: ${{ secrets.NEWGISTICS_FACILITY_ID }}
        NEWGISTICS_MERCHANT_ID: ${{ secrets.NEWGISTICS_MERCHANT_ID }}
        NEWGISTICS_SHIPPINGAPI_URL: ${{ secrets.NEWGISTICS_SHIPPINGAPI_URL }}

    - name: Notify Slack
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '${{ github.repository }} - Tests '
        channel: '#development'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'